## LIBRARIES

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## EXPLICACIÓN TEÓRICA

**TEORÍA**

Existen dos funciones que se pueden utilizar con numpy para poder realizar evaluaciones (contraciones) tensoriales y estas son einsum y tensordot. En ambos casos el funcionamiento es similar, se debe especificar bajo que ejes se quiere realizar la contracción. Por ejemplo, si tenemos un tensor $T = [2\times 3 \times4]$ y un vector $v = [1 \times 3]$ podríamos considerar el producto tensorial $T \otimes v$ y realizar la contracción por el eje j. Por lo tanto $T \otimes _j v$ sería un elemento de $ [2\times 4]$.

Por último veamos un par de ejemplos de cálculo numérico para ver como nos quedan los resultados. Sea $$T =\begin{bmatrix}
    \begin{bmatrix}
        1 & 2 \\
        3 & 4
    \end{bmatrix}
    &
    \begin{bmatrix}
        -1 & -2 \\
        -3 & -4
    \end{bmatrix}
\end{bmatrix} $$
y sea $v=[10,100]$. Entonces realizar la multiplicación tensorial por el eje i sería lo mismo que realizar $v \otimes _i T$ (es decir colocar el vector v a lo largo del eje i)
$$v \otimes _i T = 10*\begin{bmatrix}
        1 & 2 \\
        3 & 4
    \end{bmatrix} + 100*\begin{bmatrix}
        -1 & -2 \\
        -3 & -4
    \end{bmatrix} = \begin{bmatrix}
        -90 & -180 \\
        -270 & -360
    \end{bmatrix}$$

Si por el contrario hacemos la multiplicación a lo largo del eje k tendríamos que:

$$v \otimes _k T = 10*\begin{bmatrix}
        1 & 3 \\
        -1 & -3
    \end{bmatrix} + 100*\begin{bmatrix}
        2 & 4 \\
        -2 & -4
    \end{bmatrix} = \begin{bmatrix}
        210 & 430 \\
        -210 & -430
    \end{bmatrix}$$

In [8]:
##https://medium.com/analytics-vidhya/tensordot-explained-6673cfa5697f



import numpy as np

# Create a tensor of shape (2, 2, 2)
tensor = np.array([1,2,3,4,-1,-2,-3,-4]).reshape(2, 2, 2)
print('tensor',tensor)

# Create a vector of shape (1, 2)
vector = np.array([10, 100]).reshape(1, 2)
print('vector',vector)

# Multiply along the i-axis using einsum
print('Multiply along the i-axis using einsum \n')
result = np.einsum('ij,jkl->ikl', vector, tensor)
print(result,'\n')

# Multiply along the j-axis using einsum
print('Multiply along the j-axis using einsum\n')
result = np.einsum('ij,kjl->ikl', vector, tensor)
print(result,'\n')

# Multiply along the k-axis using einsum
print('Multiply along the k-axis using einsum\n')
result = np.einsum('ij,klj->ikl', vector, tensor)
print(result,'\n')

### OTRA FORMA DE HACER LO MISMO

# Given data
print('-------- Usando Tensordot --------')
vector = np.array([10, 100]).reshape(1, 2)
tensor = np.array([1, 2, 3, 4, -1, -2, -3, -4]).reshape(2, 2, 2)
# Multiply along the i-axis using tensordot ## Contrae el eje 1 con el eje 2
result = np.tensordot(vector, tensor, axes=([1], [2]))

print(result)


tensor [[[ 1  2]
  [ 3  4]]

 [[-1 -2]
  [-3 -4]]]
vector [[ 10 100]]
Multiply along the i-axis using einsum 

[[[ -90 -180]
  [-270 -360]]] 

Multiply along the j-axis using einsum

[[[ 310  420]
  [-310 -420]]] 

Multiply along the k-axis using einsum

[[[ 210  430]
  [-210 -430]]] 

-------- Usando Tensordot --------
[[[ 210  430]
  [-210 -430]]]
